title: Kosi Madukwe, Ph.D
logo: assets/images/IMG_3607.JPG
description: Over 5 years of experience specializing in transforming business challenges into technical solutions and building client relationships. 
Leverages research, technical proficiency, advanced analytics and curiosity to transform raw data and create products that empower self-service and data-driven decision-making. 
Collaborates across cross-functional teams to deliver outcomes that overcome process limitations and enhance organizational performance while incorporating integrity, empathy, and teaming. 
show_downloads : true
theme: jekyll-theme-minimal
