title: Kosi Madukwe, Ph.D
logo: assets/images/Kosi Profile Picture small.jpg
description: 5+ years transforming business challenges into technical solutions and building client relationships with integrity and empathy. Uses research, technical proficiency and curiosity to transform raw data and create products that empower self-service and data-driven decision-making.   
show_downloads : true
theme: jekyll-theme-minimal
