title: Kosi Madukwe, Ph.D
logo: assets/images/Kosi Profile Picture small.jpg
description: 8+ years turning business challenges into technical solutions. Transforms raw data with research and technical expertise. Creates products for self-service and data-driven decisions. Builds client relationships with integrity and empathy.  
show_downloads : true
theme: jekyll-theme-minimal
