title: Kosi Madukwe, Ph.D
logo: assets/images/Kosi Profile Picture small.jpg
description: 8+ years transforming business challenges into technical solutions. Building client relationships with integrity and empathy. Transforms raw data with research and technical proficiency. Creates products that empower self-service and data-driven decision-making.   
show_downloads : true
theme: jekyll-theme-minimal
