title: Kosi Madukwe, Ph.D
logo: assets/images/Profile Picture_.jpg
description: Over 5 years transforming business challenges into technical solutions and building client relationships. Leverages research, technical proficiency, advanced analytics and curiosity to transform raw data and create products that empower self-service and data-driven decision-making. Collaborates with cross-functional teams to deliver process improving outcomes while incorporating integrity and empathy. 
show_downloads : true
theme: jekyll-theme-minimal
